// Generated by build.mjs. Do not edit by hand.
window.TD_CATALOGUE = {
  "sti-bundle": {
    "title": "7-in-1 STI Test Bundle",
    "shortTitle": "7-in-1",
    "bundle": true,
    "price": 59.95,
    "compareAt": 86.75,
    "image": "assets/test-discreet-bundle-hero.webp"
  },
  "core-4": {
    "title": "Core 4 Bundle",
    "shortTitle": "Core 4",
    "bundle": true,
    "price": 39.95,
    "compareAt": 50.85,
    "image": "assets/test-discreet-core-4-pack.webp"
  },
  "chlamydia-gonorrhoea": {
    "title": "Chlamydia & Gonorrhoea Test",
    "shortTitle": "Chlamydia & Gonorrhoea",
    "bundle": false,
    "price": 17.95,
    "compareAt": 24.95,
    "image": "assets/test-discreet-chlamydia-gonorrhoea-pack.webp"
  },
  "hiv": {
    "title": "HIV 1/2 Test",
    "shortTitle": "HIV 1/2",
    "bundle": false,
    "price": 17.95,
    "compareAt": 24.95,
    "image": "assets/test-discreet-hiv-pack.webp"
  },
  "syphilis": {
    "title": "Syphilis Test",
    "shortTitle": "Syphilis",
    "bundle": false,
    "price": 14.95,
    "compareAt": 19.95,
    "image": "assets/test-discreet-syphilis-pack.webp"
  },
  "hsv-2": {
    "title": "HSV-2 Genital Herpes Test",
    "shortTitle": "HSV-2",
    "bundle": false,
    "price": 17.95,
    "compareAt": 24.95,
    "image": "assets/test-discreet-hsv-2-pack.webp"
  },
  "hep-b-c": {
    "title": "Hepatitis B & C Test",
    "shortTitle": "Hepatitis B & C",
    "bundle": false,
    "price": 17.95,
    "compareAt": 24.95,
    "image": "assets/test-discreet-hep-b-c-pack.webp"
  },
  "psa": {
    "title": "PSA Prostate Test",
    "shortTitle": "PSA",
    "bundle": false,
    "price": 17.95,
    "compareAt": 24.95,
    "image": "assets/test-discreet-psa-pack.webp"
  }
};
window.TD_BUNDLE = 'sti-bundle';
