// Cart, cookie consent and interactions. localStorage-backed for the static
// preview; the Shopify theme swaps this for the native cart API.
// Product data comes from catalogue.js, generated by build.mjs.

const CATALOGUE = window.TD_CATALOGUE || {};
const BUNDLE = window.TD_BUNDLE || 'sti-bundle';
const KEY = 'td-cart';

const money = (n) => '£' + n.toFixed(2);
const isBundle = (h) => h === BUNDLE || h === 'core-4';

// Only known handles with sane integer quantities survive a read, so a stale
// or hand-edited localStorage value can never break rendering.
function getCart() {
  let raw;
  try { raw = JSON.parse(localStorage.getItem(KEY)) || {}; } catch { raw = {}; }
  const cart = {};
  for (const [h, q] of Object.entries(raw)) {
    if (CATALOGUE[h] && Number.isInteger(q) && q > 0) cart[h] = Math.min(q, 99);
  }
  return cart;
}
const setCart = (c) => {
  try { localStorage.setItem(KEY, JSON.stringify(c)); } catch { /* storage blocked: cart lives for this page only */ }
  render();
};

function add(handle, qty = 1) {
  if (!CATALOGUE[handle]) return;
  const cart = getCart();
  cart[handle] = Math.min((cart[handle] || 0) + qty, 99);
  if (cart[handle] <= 0) delete cart[handle];
  setCart(cart);
}

function render() {
  const cart = getCart();
  const entries = Object.entries(cart);
  const count = entries.reduce((n, [, q]) => n + q, 0);
  const subtotal = entries.reduce((n, [h, q]) => n + CATALOGUE[h].price * q, 0);
  const compareTotal = entries.reduce((n, [h, q]) => n + (CATALOGUE[h].compareAt || CATALOGUE[h].price) * q, 0);
  const saving = compareTotal - subtotal;

  document.querySelectorAll('[data-cart-count]').forEach((el) => (el.textContent = count));
  const subEl = document.querySelector('[data-cart-subtotal]');
  if (subEl) subEl.innerHTML = (saving > 0 ? `<s>${money(compareTotal)}</s> ` : '') + money(subtotal);
  const saveEl = document.querySelector('[data-cart-saving]');
  if (saveEl) saveEl.textContent = saving > 0 ? `You save ${money(saving)}` : '';

  const list = document.querySelector('[data-cart-items]');
  if (list) {
    list.innerHTML = entries.length
      ? entries.map(([h, q]) => {
          const p = CATALOGUE[h];
          return `<div class="line-item">
<img src="${p.image}" alt="">
<div><h4>${p.title}</h4><div class="li-price">${money(p.price)}${p.compareAt ? `<s>${money(p.compareAt)}</s>` : ''}</div>
<div class="qty"><button data-qty="${h}:-1" aria-label="Decrease ${p.title} quantity">−</button><span>${q}</span><button data-qty="${h}:1" aria-label="Increase ${p.title} quantity">+</button></div></div>
<button class="li-remove" data-remove="${h}">Remove</button>
</div>`;
        }).join('')
      : '<p class="drawer-empty">Your cart is empty.</p>';
  }

  // Cross-sell rail: everything not yet in the cart, bundles first. No heading; the cards speak
  // for themselves. The one exception is the bundle nudge, which carries a price argument.
  const railWrap = document.querySelector('[data-cart-rail]');
  if (railWrap) {
    const rail = railWrap.querySelector('[data-rail]');
    const head = railWrap.querySelector('[data-rail-head]');
    const others = Object.entries(CATALOGUE).filter(([h]) => !cart[h]).sort(([, a], [, b]) => Number(b.bundle) - Number(a.bundle));
    const singlesCount = entries.filter(([h]) => !isBundle(h) && h !== 'psa').reduce((n, [, q]) => n + q, 0);
    railWrap.hidden = entries.length === 0 || others.length === 0;
    const nudge = singlesCount >= 2 && !cart[BUNDLE] && CATALOGUE[BUNDLE];
    head.hidden = !nudge;
    head.textContent = nudge ? `The 7-in-1 covers all seven STIs for ${money(CATALOGUE[BUNDLE].price)}` : '';
    rail.innerHTML = others.map(([h, p]) => `<div class="rail-card">
<img class="rail-thumb" src="${p.image}" alt="">
<div class="rail-body"><span class="rail-title">${p.shortTitle}</span><span class="rail-price">${money(p.price)}${p.compareAt ? ` <s>${money(p.compareAt)}</s>` : ''}</span></div>
<button class="rail-add" data-add="${h}" aria-label="Add ${p.title}">+</button>
</div>`).join('');
    rail.scrollLeft = 0;
  }

  // Empty cart: checkout goes nowhere, so disable the link.
  document.querySelectorAll('[data-checkout-link]').forEach((el) => el.classList.toggle('is-disabled', count === 0));

  const summary = document.querySelector('[data-checkout-summary]');
  if (summary) {
    summary.innerHTML = entries.length
      ? entries.map(([h, q]) => `<div class="sum-line"><span>${CATALOGUE[h].title} × ${q}</span><b>${money(CATALOGUE[h].price * q)}</b></div>`).join('') +
        `<div class="sum-total"><span>Total</span><span>${saving > 0 ? `<s>${money(compareTotal)}</s> ` : ''}${money(subtotal)}</span></div>`
      : '<p class="sum-empty">Your cart is empty.</p>';
  }
}

let cartTrigger = null;
function openCart() {
  cartTrigger = document.activeElement;
  document.body.classList.add('cart-open');
  document.querySelectorAll('[data-cart-open]').forEach((b) => b.setAttribute('aria-expanded', 'true'));
  document.getElementById('cart-drawer')?.focus();
}
function closeCart() {
  document.body.classList.remove('cart-open');
  document.querySelectorAll('[data-cart-open]').forEach((b) => b.setAttribute('aria-expanded', 'false'));
  if (cartTrigger && document.contains(cartTrigger)) cartTrigger.focus();
  cartTrigger = null;
}

document.addEventListener('click', (e) => {
  const addBtn = e.target.closest('[data-add]');
  if (addBtn) { e.preventDefault(); e.stopPropagation(); add(addBtn.dataset.add); openCart(); return; }
  if (e.target.closest('[data-cart-open]')) { openCart(); return; }
  if (e.target.closest('[data-cart-close]')) { closeCart(); return; }
  const qty = e.target.closest('[data-qty]');
  if (qty) { const [h, d] = qty.dataset.qty.split(':'); add(h, Number(d)); return; }
  const rm = e.target.closest('[data-remove]');
  if (rm) { const c = getCart(); delete c[rm.dataset.remove]; setCart(c); return; }
  const consent = e.target.closest('[data-consent]');
  if (consent) {
    localStorage.setItem('td-consent', consent.dataset.consent);
    document.querySelector('[data-cookie-banner]')?.classList.remove('show');
    return;
  }
});
document.addEventListener('keydown', (e) => { if (e.key === 'Escape') closeCart(); });
// Keep the badge in sync when another tab changes the cart.
window.addEventListener('storage', (e) => { if (e.key === KEY) render(); });

// Reviews carousel arrows
document.addEventListener('click', (e) => {
  const nav = e.target.closest('[data-scroll]');
  if (!nav) return;
  const track = document.querySelector('[data-reviews]');
  if (track) track.scrollBy({ left: Number(nav.dataset.scroll) * 400, behavior: 'smooth' });
});

// Cross-sell rail drifts slowly (about 28px a second) while the drawer is open: to the end, a short
// rest, then back. Every product appears once. Pauses on hover, focus or touch so it can be read and
// swiped, and stays still under prefers-reduced-motion.
(() => {
  const rail = document.querySelector('[data-rail]');
  if (!rail || matchMedia('(prefers-reduced-motion: reduce)').matches) return;
  let paused = false;
  let holdUntil = 0;
  let dir = 1;
  let pos = null;
  let last = performance.now();
  const pause = () => { paused = true; };
  const resume = (delay) => { paused = false; holdUntil = performance.now() + delay; };
  rail.addEventListener('mouseenter', pause); rail.addEventListener('mouseleave', () => resume(600));
  rail.addEventListener('focusin', pause); rail.addEventListener('focusout', () => resume(600));
  rail.addEventListener('touchstart', pause, { passive: true }); rail.addEventListener('touchend', () => resume(3000), { passive: true });
  const tick = (now) => {
    const dt = Math.min(now - last, 50); last = now;
    const max = rail.scrollWidth - rail.clientWidth;
    const running = !paused && now >= holdUntil && max > 4 && document.body.classList.contains('cart-open') && !rail.closest('[hidden]');
    if (running) {
      if (pos === null || Math.abs(pos - rail.scrollLeft) > 2) pos = rail.scrollLeft; // pick up manual scrolls
      pos += dir * dt * 0.028;
      if (pos >= max) { pos = max; dir = -1; holdUntil = now + 1500; }
      if (pos <= 0) { pos = 0; dir = 1; holdUntil = now + 1500; }
      rail.scrollLeft = pos;
    } else {
      pos = null;
    }
    requestAnimationFrame(tick);
  };
  requestAnimationFrame(tick);
})();

// Cookie banner: show until a choice is stored.
if (!localStorage.getItem('td-consent')) {
  document.querySelector('[data-cookie-banner]')?.classList.add('show');
}

// Sticky mobile add-to-cart: show once the main buy button has scrolled up behind the sticky
// header (64px), so there is no dead zone where neither control is usable. A passive scroll
// listener with one rect read per frame; IntersectionObserver was tried and an observer created
// during page load never reported a change in Chromium, so it is not used here.
const mainAtc = document.querySelector('.pdp-buy [data-add]');
const sticky = document.querySelector('[data-sticky-atc]');
if (mainAtc && sticky) {
  let queued = false;
  const update = () => { queued = false; sticky.classList.toggle('show', mainAtc.getBoundingClientRect().bottom < 64); };
  const schedule = () => { if (!queued) { queued = true; requestAnimationFrame(update); } };
  addEventListener('scroll', schedule, { passive: true });
  addEventListener('resize', schedule, { passive: true });
  update();
}

render();
